# Generated by Django 5.1.3 on 2024-11-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
