# Generated by Django 5.1.3 on 2024-12-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0003_alter_emailverification_verification_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
