# Generated by Django 5.1.3 on 2024-12-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0005_task_task_image_1_mob_task_task_image_2_mob_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="task_test",
        ),
        migrations.AddField(
            model_name="task",
            name="intro_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="task",
            name="teleport_image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_image_2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_image_2_mob",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_image_3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_image_3_mob",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
