# Generated by Django 5.1.3 on 2024-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0006_remove_task_task_test_task_intro_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="verification_code",
            field=models.CharField(max_length=6),
        ),
    ]
