# Generated by Django 5.1.3 on 2024-12-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0007_alter_emailverification_verification_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="fail_text",
            field=models.TextField(null=True),
        ),
    ]
