# Generated by Django 5.1.3 on 2024-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0008_task_fail_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="video_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
