# Generated by Django 5.1.3 on 2024-12-06 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advent_app", "0010_task_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.AddField(
            model_name="taskresponse",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
